services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/healthcheck"]
      interval: 30s
      start_interval: 10s
      start_period: 10s
      timeout: 30s
      retries: 10
    develop:
      watch:
        - path: ./backend/src
          action: rebuild
        - path: ./backend/Cargo.toml
          action: rebuild
    volumes:
      - ./backend:/code
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:keyboard_cat@database:5432/postgres
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: keyboard_cat
    volumes:
      - ./backend/db_init:/docker-entrypoint-initdb.d
    healthcheck:
      interval: 1m
      retries: 10
      start_interval: 1s
      start_period: 5s
      test: ["CMD-SHELL", "psql -U postgres -c 'select * from agile_game;'"]
      timeout: 30s
    ports:
      - 5432:5432
