services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthcheck"]
      interval: 30s
      start_interval: 10s
      start_period: 10s
      timeout: 30s
      retries: 10
    develop:
      watch:
        - path: ./backend/src
          action: rebuild
        - path: ./backend/Cargo.toml
          action: rebuild
    volumes:
      - ./backend:/code
