[package]
name = "anathema_frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
anathema = "0.2.11"
anathema-extras = "0.1.0"
reqwest = { version = "0.13.0", features = ["json", "blocking"] }
serde_json = "1.0.148"
serde = "1.0.228"
